name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: |
          cd custom_components/ooni_connect
          zip -r ooni_connect.zip .

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: custom_components/ooni_connect/ooni_connect.zip
